### PR TITLE
Added missing AcceptOrDecline argument

### PR DESCRIPTION
**Pull request by navybluesilver**
Contracts are always being declined when using the accept command. This is because the AcceptOrDecline argument is missing.

### CODE REVIEW

**Comment by Varunram** [comment]
retest this please

**Comment by Varunram** [comment]
I think this is due to the many rebases  we’ve had, thanks!

**Comment by delbonis** [comment]
Yeah maybe we should consider writing tests for `lit-af` itself?

And the reason the argument is named `aor` is because it referred to "Accept or Reject" in other places, perhaps we should rename things to be more internally-consistent.

**Comment by Varunram** [comment]
This is actually because we didn't follow set standards for merging of PRs. Please refer to my comment at #319.

**Comment by infografx** [comment]
Hello guys. Could you tell me please, why there is no "DeleteContract" function in the master branch.

Should some work be done in this direction?

**Pull request merged**
