### PR TITLE
Better Coin Selection based on Electrum

### PR DESCRIPTION
**Pull request by Varunram**
Well, the idea is to implement something like the privacy approach follows in Electrum, so that we can choose coins in a better way.

As of now, the PR has a couple of helper functions and uses the current coin selection algo as fall-back (the seed is a constant right now). Will continue to update this PR.

### CODE REVIEW

**Comment by Varunram** [comment]
Revisiting this, might be worth to see how Core implements Murch's algo, now that it is merged over there.

**Comment by alindr** [comment]
it's a good idea to have a better coin selection mechanism, but the Electrum one is not the right approach.

**Comment by Varunram** [comment]
Well, that depends ;  bitcoin core has a very nice selection mechanism (Murch's algorithm) that was merged for the last release, but its overkill for what we're doing at this moment. Electrum is better in some cases than what we have right now (better when your utxos are of similar size) and worse at some (huge differences in utxos size), so its really up to us to decide on an algo.

**Comment by Varunram** [comment]
Closing this for now.

**Pull request closed without merging**
