### PR TITLE
Converted all the `fmt.Printf` statements to `log.Printf` statements.

### PR DESCRIPTION
**Pull request by delbonis**
Suggested in the comments on #204.  Although I didn't base it off of that branch in the PR so there might be some trivial merge conflicts maybe.

### CODE REVIEW

**Comment by delbonis** [comment]
Oh crap what did I do?

**Comment by Varunram** [comment]
you didn't initialise `log` in `walletcmds.go` :)

**Comment by Varunram** [comment]
I think `fat` statements are better in lit-af since they're less ugly without the timestamp, although that's entirely my opinion on it.

**Comment by delbonis** [comment]
Reverted.

**Pull request merged**
