### PR TITLE
Basic lightning integration test

### PR DESCRIPTION
**Pull request by vinchang2015**
- creating a regtest node to support mineblock(), sendTo(), getInfo() functional calls
- creating a litconn node to support litNewAddress(), litSend(), getWitAddress(), getLegacyAddress() and getBal() functional calls
- creating the first test_receive file to test the process of setting up a regtest node and a lit node and the ability of a lit node to receive money from the regtest node

### CODE REVIEW

**Comment by jnewbery** [comment]
@vinchang2015 - can you rebase onto master squash these commits down. I'll review once the commits have been cleaned up. Thanks!

**Comment by jnewbery** [comment]
I've tried running `test_receive.py` locally and it fails for me, with lit never starting. Removing the try/except handling around the `LitConn()` instantiation I see that the call to websocket is failing:

```
→ ./test_receive.py 
Bitcoin server stopping
Bitcoin server starting
starting lit...
Traceback (most recent call last):
  File "./test_receive.py", line 111, in <module>
    main(sys.argv)
  File "./test_receive.py", line 75, in main
    litConn = LitConn()
  File "/home/ubuntu/go/src/github.com/mit-dci/lit/cmd/litpy/litrpc.py", line 83, in __init__
    self.ws = websocket.WebSocket()
TypeError: __init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
```

I got websocket by running `pip3 install websocket`. Is that the correct module?

**Comment by vinchang2015** [comment]
> I got websocket by running pip3 install websocket. Is that the correct module?

I believe the `pip3 install websocket-client` is the right command. 

We'll rebase and merge with the master later this week.

**Comment by vinchang2015** [comment]
@jnewbery PTAL, thanks

**Comment by jnewbery** [comment]
This completely reverts all of the recent changes on master (and therefore breaks test_lit.py)

I recommend you take a look at https://www.atlassian.com/git/tutorials/merging-vs-rebasing . The master branch has changed quite a lot since you branched off it - you'll need to pick out the changes you want to PR and rebase them on top of the current master branch.

**Comment by vinchang2015** [comment]
superceded by #54

**Pull request closed without merging**
