### PR TITLE
Basic Config File Parsing

### PR DESCRIPTION
**Pull request by Varunram**
This PR aims to accomplish config file parsing to some extent. As of now, it can parse params in `config/`. Will keep constantly updating this branch under @adiabat's suggestions and inputs.

### CODE REVIEW

**Comment by adiabat** [comment]
You put your privatekey in here, also a binary file.  Might want to get rid of that :)

I'll look at viper more, but I think the code from btcd handling the config file looks like a better fit for this use case.

**Comment by Varunram** [comment]
Thanks a ton @adiabat and sorry!

**Comment by Varunram** [comment]
Yeah, makes sense. I'll checkout btcd, prune their stuff and update this PR :)

**Comment by Varunram** [comment]
@adiabat Updated updated!

**Comment by adiabat** [comment]
Cool, thanks for writing this! 

One feature I use quite a lot is the -dir flag, to specify a directory for all the lit files.  For normal usage it's probably not that important, but right now it's useful for testing by having multiple lit nodes running on a single machine.  Right now this config file PR doesn't work nicely with that feature; it seems to only work with the default datadir, $HOME/.lit.  

I think the most straightforward way to support custom directories would be to parse command line args first, and if it sees a -dir flag, to look for a lit.conf in that directory along with everything else.

If that seems annoying we can merge this first with only single directory support; in fact maybe for the custom directory case, having a config file isn't as important.  However, the -dir flag should still work, and if it can't find the lit.conf, it ignore it and not require one.

**Comment by Varunram** [comment]
Done, a couple of small things though, the `-dir` flag must be specified as a whole instead of just being relative to the binary (we could change that, but this would address more use cases). Also, I decided to remove the `-c` option earlier as I thought it didn't make sense to have the config file and  home directories in separate places. If the config file has been deleted in the specified home directory, a new default config file will be generated.

**Comment by Varunram** [comment]
Rebased on master. I did my best to incorporate the tower code in here, please do tell if there are any unintended bugs over here. Thanks!

**Comment by adiabat** [comment]
Looks good!  I will add / modify this a bit afterwords but this looks good.  I'll probably add a hardcoded starting settings lit.conf with comments in it for people to edit.

**Pull request merged**
