### PR TITLE
Use SSL instead of WebSockets

### PR DESCRIPTION
**Pull request by Varunram**

### CODE REVIEW

**Comment by adiabat** [comment]
This breaks all the tests, which use websockets.  It'd break them anyway with just the addition of TLS, but the websockets also.  I think it's easier to leave websockets in for now and not change the tests (unless the client also has to do some new stuff to use the certs)

**Comment by Varunram** [comment]
Done!

**Comment by Varunram** [comment]
A hack yfix for python tests (they don't check the SSL cert's authenticity), but should hold until we move completely to tls and have new tests (hopefully).

**Comment by Varunram** [comment]
Moved the entire test suite to TLS in #143.

**Pull request closed without merging**
