### PR TITLE
Switch to chain containing more work

### PR DESCRIPTION
**Pull request by Varunram**
Switch to the chain containing more work from the longer chain mechanism that we follow currently.

### CODE REVIEW

**Comment by adiabat** [comment]
Added some comments; testing with regtest and invalidateblock, I can still get reorgs to work based on height, but I get the `Chains don't start with the same header. Quitting.!` message every time, so it's seems like the PoW comparison isn't working.

**Comment by Varunram** [comment]
Hm, that seems strange.. That should fire in the case both chains don't start off with the same merkle root. Did the chains you were testing with have the same root?

**Comment by adiabat** [comment]
Yeah I was just doing re-orgs on regtest using `invalidateblock`, then `generate`, got that message every time.  Do you get different behavior on yours?

**Comment by metalicjames** [comment]
retest this please

**Pull request merged**
