### PR TITLE
Pulled btcd/btcutil dependencies into project, removing vendor directory.

### PR DESCRIPTION
**Pull request by delbonis**
Hopefully this all looks nicer now.

There's still some things that need to be moved around and cleaned up (like unused dependencies), but this is most of the way there.

### CODE REVIEW

**Comment by Varunram** [comment]
Merge conflicts :(

**Comment by delbonis** [comment]
It should just be a matter of swapping out the import URLs.

**Comment by delbonis** [comment]
Oh thank god that didn't actually merge it into master when I used the webui.

**Comment by Varunram** [comment]
The button will be greyed out anyway, so no problems. Build still failing though
```
FAIL	github.com/mit-dci/lit/uspv
```

**Comment by delbonis** [comment]
oh great now how do I fix that?

**Comment by delbonis** [comment]
Fixed it!

**Comment by Varunram** [comment]
yep :)

**Comment by alindr** [comment]
Alin to reach out to Tadge to merge this PR.

**Pull request merged**
