### PR TITLE
Cleaned up new btcutil stuff, removing some redundancies

### PR DESCRIPTION
**Pull request by delbonis**
This fully splits apart the btcd stuff, getting rid of everything I could tell that could be removed.  Also I updated the README a bit, adding a bit more documentation.

### CODE REVIEW

**Comment by delbonis** [comment]
There's a lot of refactoring that I'm thinking about how to actually go about that would reduce the need for scarier rebases later on by slimming down the dependency graph between components in Lit.  Gonna wait until after we have HTLCs merged.

**Comment by delbonis** [comment]
Oh dear this is quite a messy merge.

**Comment by delbonis** [comment]
Ok that should be good now.  Not sure why it says "2 days ago".

**Comment by gertjaap** [comment]
Checked out the code and basic functionality is in tact.

**Pull request merged**
